"""Daily performance report: gather metrics and send email."""

import logging
import smtplib
from datetime import datetime, timezone, timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import config
from db.supabase_client import get_client

logger = logging.getLogger(__name__)


def _since_yesterday_utc() -> str:
    """ISO cutoff for 'since yesterday' (start of previous calendar day UTC)."""
    now = datetime.now(timezone.utc)
    yesterday = (now - timedelta(days=1)).replace(hour=0, minute=0, second=0, microsecond=0)
    return yesterday.isoformat()


def _fetch_report_data() -> dict:
    """Fetch from Supabase (and optionally Alpaca) for the last 24h / yesterday."""
    cutoff = _since_yesterday_utc()
    client = get_client()
    data = {
        "period_start": cutoff,
        "news_articles": 0,
        "reddit_posts": 0,
        "sentiment_scores": 0,
        "signals_buy": 0,
        "signals_sell": 0,
        "signals_hold": 0,
        "trades_placed": 0,
        "trades_filled": 0,
        "trades_pending": 0,
        "portfolio_value": None,
        "open_positions": None,
    }
    try:
        r = client.table("news_articles").select("id", count="exact").gte("fetched_at", cutoff).execute()
        data["news_articles"] = r.count if getattr(r, "count", None) is not None else len(r.data or [])
    except Exception as e:
        logger.warning("Report: news count failed: %s", e)
    try:
        r = client.table("reddit_posts").select("id", count="exact").gte("fetched_at", cutoff).execute()
        data["reddit_posts"] = r.count if getattr(r, "count", None) is not None else len(r.data or [])
    except Exception as e:
        logger.warning("Report: reddit count failed: %s", e)
    try:
        r = client.table("sentiment_scores").select("id", count="exact").gte("scored_at", cutoff).execute()
        data["sentiment_scores"] = r.count if getattr(r, "count", None) is not None else len(r.data or [])
    except Exception as e:
        logger.warning("Report: sentiment count failed: %s", e)
    try:
        r = client.table("trade_signals").select("direction").gte("generated_at", cutoff).execute()
        for row in r.data or []:
            d = (row.get("direction") or "HOLD").upper()
            if d == "BUY":
                data["signals_buy"] += 1
            elif d == "SELL":
                data["signals_sell"] += 1
            else:
                data["signals_hold"] += 1
    except Exception as e:
        logger.warning("Report: signals failed: %s", e)
    try:
        r = client.table("trades").select("status").gte("created_at", cutoff).execute()
        for row in r.data or []:
            s = (row.get("status") or "").lower()
            data["trades_placed"] += 1
            if s == "filled":
                data["trades_filled"] += 1
            elif s in ("pending", "new", "accepted"):
                data["trades_pending"] += 1
    except Exception as e:
        logger.warning("Report: trades failed: %s", e)
    if config.ALPACA_API_KEY and config.ALPACA_SECRET_KEY:
        try:
            from execution.alpaca_client import get_client as get_alpaca
            alpaca = get_alpaca()
            account = alpaca.get_account()
            data["portfolio_value"] = float(getattr(account, "portfolio_value", 0) or account.get("portfolio_value", 0) or 0)
            positions = alpaca.list_positions()
            data["open_positions"] = len(positions or [])
        except Exception as e:
            logger.warning("Report: Alpaca portfolio failed: %s", e)
    return data


def _build_email_body(data: dict) -> str:
    """Plain-text and HTML body for the report."""
    period = data["period_start"][:10]
    lines = [
        f"Trading Agent — Daily Performance Report ({period})",
        "",
        "— Ingestion —",
        f"  News articles:     {data['news_articles']}",
        f"  Reddit posts:      {data['reddit_posts']}",
        "",
        "— NLP —",
        f"  Sentiment scores:  {data['sentiment_scores']}",
        "",
        "— Signals (last 24h) —",
        f"  BUY:   {data['signals_buy']}",
        f"  SELL:  {data['signals_sell']}",
        f"  HOLD:  {data['signals_hold']}",
        "",
        "— Trades —",
        f"  Placed:  {data['trades_placed']}",
        f"  Filled:  {data['trades_filled']}",
        f"  Pending: {data['trades_pending']}",
    ]
    if data.get("portfolio_value") is not None:
        lines.extend([
            "",
            "— Portfolio (Alpaca) —",
            f"  Portfolio value:  ${data['portfolio_value']:,.2f}",
            f"  Open positions:   {data['open_positions']}",
        ])
    lines.append("")
    lines.append("—")
    lines.append("Generated by stock-trading-agent")
    return "\n".join(lines)


def _send_email(to: str, subject: str, body_plain: str) -> bool:
    """Send email via SMTP. Returns True if sent."""
    if not config.SMTP_USER or not config.SMTP_PASSWORD:
        logger.warning("SMTP credentials not set; skipping daily report email.")
        return False
    from_addr = config.REPORT_EMAIL_FROM or config.SMTP_USER
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = to
    msg.attach(MIMEText(body_plain, "plain"))
    try:
        with smtplib.SMTP(config.SMTP_HOST, config.SMTP_PORT) as server:
            server.starttls()
            server.login(config.SMTP_USER, config.SMTP_PASSWORD)
            server.sendmail(from_addr, [to], msg.as_string())
        return True
    except Exception as e:
        logger.exception("Failed to send daily report email: %s", e)
        return False


def send_daily_report() -> bool:
    """
    Gather performance data since yesterday, build report, and email to REPORT_EMAIL_TO.
    Returns True if the email was sent successfully.
    """
    to = (config.REPORT_EMAIL_TO or "").strip()
    if not to:
        logger.warning("REPORT_EMAIL_TO not set; skipping daily report.")
        return False
    data = _fetch_report_data()
    body = _build_email_body(data)
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    subject = f"Trading Agent — Daily Report ({date_str})"
    ok = _send_email(to, subject, body)
    if ok:
        logger.info("Daily report sent to %s", to)
    return ok
