-- Run this against your Supabase project (SQL Editor).

-- Raw incoming articles (Finnhub, CryptoPanic, Alpha Vantage)
CREATE TABLE IF NOT EXISTS news_articles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source TEXT,
  title TEXT,
  description TEXT,
  url TEXT UNIQUE,
  sector TEXT CHECK (sector IN ('natural_resources', 'crypto', 'quantum_computing', 'energy')),
  data_source TEXT CHECK (data_source IN ('finnhub', 'cryptopanic', 'alpha_vantage')),
  published_at TIMESTAMPTZ,
  fetched_at TIMESTAMPTZ DEFAULT now()
);

-- Raw Reddit posts/comments
CREATE TABLE IF NOT EXISTS reddit_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  subreddit TEXT,
  post_id TEXT UNIQUE,
  title TEXT,
  body TEXT,
  score INT,
  num_comments INT,
  sector TEXT CHECK (sector IN ('natural_resources', 'crypto', 'quantum_computing', 'energy')),
  created_at TIMESTAMPTZ,
  fetched_at TIMESTAMPTZ DEFAULT now()
);

-- NLP sentiment scores applied to each piece of content
CREATE TABLE IF NOT EXISTS sentiment_scores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source_type TEXT CHECK (source_type IN ('news', 'reddit')),
  source_id UUID,
  ticker TEXT,
  sector TEXT CHECK (sector IN ('natural_resources', 'crypto', 'quantum_computing', 'energy')),
  sentiment FLOAT,
  confidence FLOAT,
  model_used TEXT,
  scored_at TIMESTAMPTZ DEFAULT now()
);

-- Aggregated trade signals generated by the signal engine
CREATE TABLE IF NOT EXISTS trade_signals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticker TEXT,
  sector TEXT CHECK (sector IN ('natural_resources', 'crypto', 'quantum_computing', 'energy')),
  direction TEXT CHECK (direction IN ('BUY', 'SELL', 'HOLD')),
  confidence FLOAT,
  signal_strength FLOAT,
  source_count INT,
  generated_at TIMESTAMPTZ DEFAULT now(),
  acted_on BOOLEAN DEFAULT false
);

-- All orders sent to Alpaca
CREATE TABLE IF NOT EXISTS trades (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  signal_id UUID REFERENCES trade_signals(id),
  ticker TEXT,
  sector TEXT,
  direction TEXT,
  quantity FLOAT,
  order_type TEXT,
  limit_price FLOAT,
  stop_loss FLOAT,
  take_profit FLOAT,
  alpaca_order_id TEXT UNIQUE,
  status TEXT,
  filled_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- System event log
CREATE TABLE IF NOT EXISTS logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  level TEXT,
  component TEXT,
  message TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- If news_articles already existed without data_source, run:
-- ALTER TABLE news_articles ADD COLUMN IF NOT EXISTS data_source TEXT CHECK (data_source IN ('finnhub', 'cryptopanic', 'alpha_vantage'));
-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_news_articles_sector_fetched ON news_articles(sector, fetched_at);
CREATE INDEX IF NOT EXISTS idx_reddit_posts_sector_fetched ON reddit_posts(sector, fetched_at);
CREATE INDEX IF NOT EXISTS idx_sentiment_scores_ticker_scored ON sentiment_scores(ticker, scored_at);
CREATE INDEX IF NOT EXISTS idx_trade_signals_generated ON trade_signals(generated_at);
CREATE INDEX IF NOT EXISTS idx_trades_created ON trades(created_at);
CREATE INDEX IF NOT EXISTS idx_logs_created ON logs(created_at);
